/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.11u-20020201-2200
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGPYTHON

#ifdef __cplusplus
template<class T> class SwigValueWrapper {
    T *tt;
public:
    inline SwigValueWrapper() : tt(0) { }
    inline ~SwigValueWrapper() { if (tt) delete tt; } 
    inline SwigValueWrapper& operator=(T t) {tt = new T(t); return *this;}
    inline operator T() const {return *tt;}
    inline T *operator&() { return tt; }
};                                                    
#endif

/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__)
#       if defined(_MSC_VER)
#               if defined(STATIC_LINKED)
#                       define SWIGEXPORT(a) a
#               else
#                       define SWIGEXPORT(a) __declspec(dllexport) a
#               endif
#       else
#               if defined(__BORLANDC__)
#                       define SWIGEXPORT(a) a _export
#               else
#                       define SWIGEXPORT(a) a
#       endif
#endif
#else
#       define SWIGEXPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#define SWIGRUNTIME(a) static a
#endif



#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);

typedef struct swig_type_info {
  const char             *name;                 
  swig_converter_func     converter;
  const char             *str;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
  void                   *clientdata;	
} swig_type_info;

#ifdef SWIG_NOINCLUDE
SWIGEXPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGEXPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGEXPORT(void *) SWIG_TypeCast(swig_type_info *, void *);
SWIGEXPORT(swig_type_info *) SWIG_TypeQuery(const char *);
SWIGEXPORT(void) SWIG_TypeClientData(swig_type_info *, void *);
#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti)
{
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
 l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty)
{
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  while (s) {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
	s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      return s;
    }
    s = s->next;
  }
  return 0;
}

/* Cast a pointer (needed for C++ inheritance */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) 
{
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* Set the clientdata field for a type */
SWIGRUNTIME(void)
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata) return;
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = swig_type_list;
      while (tc) {
	if ((strcmp(tc->name, equiv->name) == 0))
	  SWIG_TypeClientData(tc,clientdata);
	tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}
#endif

#ifdef __cplusplus
}

#endif




/***********************************************************************
 * python.swg
 *
 *     This file contains the runtime support for Python modules
 *     and includes code for managing global variables and pointer
 *     type checking.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 ************************************************************************/

#include <stdlib.h>
#include "Python.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SWIG_PY_INT     1
#define SWIG_PY_FLOAT   2
#define SWIG_PY_STRING  3
#define SWIG_PY_POINTER 4
#define SWIG_PY_BINARY  5

/* Constant information structure */
typedef struct swig_const_info {
    int type;
    char *name;
    long lvalue;
    double dvalue;
    void   *pvalue;
    swig_type_info **ptype;
} swig_const_info;

#ifdef SWIG_NOINCLUDE

SWIGEXPORT(PyObject *)        SWIG_newvarlink();
SWIGEXPORT(void)              SWIG_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
SWIGEXPORT(int)               SWIG_ConvertPtr(PyObject *, void **, swig_type_info *, int);
SWIGEXPORT(int)               SWIG_ConvertPacked(PyObject *, void *, int sz, swig_type_info *, int);
SWIGEXPORT(char *)            SWIG_PackData(char *c, void *, int);
SWIGEXPORT(char *)            SWIG_UnpackData(char *c, void *, int);
SWIGEXPORT(PyObject *)        SWIG_NewPointerObj(void *, swig_type_info *,int own);
SWIGEXPORT(PyObject *)        SWIG_NewPackedObj(void *, int sz, swig_type_info *);
SWIGEXPORT(void)              SWIG_InstallConstants(PyObject *d, swig_const_info constants[]);
SWIGEXPORT(PyObject *)        SWIG_MakeShadow(PyObject *robj, swig_type_info *type, int own);
#else

/* -----------------------------------------------------------------------------
 * global variable support code.
 * ----------------------------------------------------------------------------- */

typedef struct swig_globalvar {   
  char       *name;                  /* Name of global variable */
  PyObject *(*get_attr)(void);       /* Return the current value */
  int       (*set_attr)(PyObject *); /* Set the value */
  struct swig_globalvar *next;
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar *vars;
} swig_varlinkobject;

static PyObject *
swig_varlink_repr(swig_varlinkobject *v) {
  v = v;
  return PyString_FromString("<Global variables>");
}

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags) {
  swig_globalvar  *var;
  flags = flags;
  fprintf(fp,"Global variables { ");
  for (var = v->vars; var; var=var->next) {
    fprintf(fp,"%s", var->name);
    if (var->next) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->get_attr)();
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return NULL;
}

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->set_attr)(p);
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return 1;
}

statichere PyTypeObject varlinktype = {
  PyObject_HEAD_INIT(0)              
  0,
  (char *)"swigvarlink",                      /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */
SWIGRUNTIME(PyObject *)
SWIG_newvarlink(void) {
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  result->vars = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGRUNTIME(void)
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p)) {
  swig_varlinkobject *v;
  swig_globalvar *gv;
  v= (swig_varlinkobject *) p;
  gv = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  gv->name = (char *) malloc(strlen(name)+1);
  strcpy(gv->name,name);
  gv->get_attr = get_attr;
  gv->set_attr = set_attr;
  gv->next = v->vars;
  v->vars = gv;
}

/* Pack binary data into a string */
SWIGRUNTIME(char *)
SWIG_PackData(char *c, void *ptr, int sz) {
  static char hex[17] = "0123456789abcdef";
  int i;
  unsigned char *u = (unsigned char *) ptr;
  register unsigned char uu;
  for (i = 0; i < sz; i++,u++) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* Unpack binary data from a string */
SWIGRUNTIME(char *)
SWIG_UnpackData(char *c, void *ptr, int sz) {
  register unsigned char uu;
  register int d;
  unsigned char *u = (unsigned char *) ptr;
  int i;
  for (i = 0; i < sz; i++, u++) {
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    *u = uu;
  }
  return c;
}

/* Convert a pointer value */
SWIGRUNTIME(int)
SWIG_ConvertPtr(PyObject *obj, void **ptr, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c;
  static PyObject *SWIG_this = 0;
  int    newref = 0;

  if (!obj) return 0;
  if (obj == Py_None) {
    *ptr = 0;
    return 0;
  }
#ifdef SWIG_COBJECT_TYPES
  if (!(PyCObject_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyCObject_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  *ptr = PyCObject_AsVoidPtr(obj);
  c = (char *) PyCObject_GetDesc(obj);
  if (newref) Py_DECREF(obj);
  goto cobject;
#else
  if (!(PyString_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyString_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) {
      if (newref) Py_DECREF(obj);
      return 0;
    } else {
      if (newref) Py_DECREF(obj);
      goto type_error;
    }
  }
  c++;
  c = SWIG_UnpackData(c,ptr,sizeof(void *));
  if (newref) Py_DECREF(obj);
#endif

#ifdef SWIG_COBJECT_TYPES
cobject:
#endif

  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
    *ptr = SWIG_TypeCast(tc,(void*) *ptr);
  }
  return 0;

type_error:
  if (flags) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Convert a packed value value */
SWIGRUNTIME(int)
SWIG_ConvertPacked(PyObject *obj, void *ptr, int sz, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c;

  if ((!obj) || (!PyString_Check(obj))) goto type_error;
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') goto type_error;
  c++;
  c = SWIG_UnpackData(c,ptr,sz);
  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
  }
  return 0;

type_error:

  if (flags) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Create a new pointer object */
SWIGRUNTIME(PyObject *)
SWIG_NewPointerObj(void *ptr, swig_type_info *type, int own) {
  PyObject *robj;
  if (!ptr) {
    Py_INCREF(Py_None);
    return Py_None;
  }
#ifdef SWIG_COBJECT_TYPES
  robj = PyCObject_FromVoidPtrAndDesc((void *) ptr, (char *) type->name, NULL);
#else
  {
    char result[512];
    char *r = result;
    *(r++) = '_';
    r = SWIG_PackData(r,&ptr,sizeof(void *));
    strcpy(r,type->name);
    robj = PyString_FromString(result);
  }
#endif
  if (!robj || (robj == Py_None)) return robj;
  if (type->clientdata) {
    PyObject *inst;
    PyObject *args = Py_BuildValue((char*)"(O)", robj);
    Py_DECREF(robj);
    inst = PyObject_CallObject((PyObject *) type->clientdata, args);
    Py_DECREF(args);
    if (own) {
      PyObject *n = PyInt_FromLong(1);
      PyObject_SetAttrString(inst,(char*)"thisown",n);
      Py_DECREF(n);
    }
    robj = inst;
  }
  return robj;
}

SWIGRUNTIME(PyObject *)
SWIG_MakeShadow(PyObject *robj, swig_type_info *type, int own) {
  if (!robj || (robj == Py_None)) return robj;
  if (type->clientdata) {
    PyInstanceObject *inst;
    inst = PyObject_NEW(PyInstanceObject, &PyInstance_Type);
    if (!inst) return robj;
    inst->in_dict = PyDict_New();
    inst->in_class = (PyClassObject *) type->clientdata;
    Py_INCREF(inst->in_class);
    PyObject_SetAttrString((PyObject *)inst,(char*)"this",robj);
    Py_DECREF(robj);
    if (own) {
      PyObject *n = PyInt_FromLong(1);
      PyObject_SetAttrString((PyObject *)inst,(char*)"thisown",n);
      Py_DECREF(n);
    }
    robj = (PyObject *) inst;
    Py_INCREF(robj);
  }
  return robj;
}

SWIGRUNTIME(PyObject *)
SWIG_NewPackedObj(void *ptr, int sz, swig_type_info *type) {
  char result[1024];
  char *r = result;
  if ((2*sz + 1 + strlen(type->name)) > 1000) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  strcpy(r,type->name);
  return PyString_FromString(result);
}

/* Install Constants */
SWIGRUNTIME(void)
SWIG_InstallConstants(PyObject *d, swig_const_info constants[]) {
  int i;
  PyObject *obj;
  for (i = 0; constants[i].type; i++) {
    switch(constants[i].type) {
    case SWIG_PY_INT:
      obj = PyInt_FromLong(constants[i].lvalue);
      break;
    case SWIG_PY_FLOAT:
      obj = PyFloat_FromDouble(constants[i].dvalue);
      break;
    case SWIG_PY_STRING:
      obj = PyString_FromString((char *) constants[i].pvalue);
      break;
    case SWIG_PY_POINTER:
      obj = SWIG_NewPointerObj(constants[i].pvalue, *(constants[i]).ptype,0);
      break;
    case SWIG_PY_BINARY:
      obj = SWIG_NewPackedObj(constants[i].pvalue, constants[i].lvalue, *(constants[i].ptype));
      break;
    default:
      obj = 0;
      break;
    }
    if (obj) {
      PyDict_SetItemString(d,constants[i].name,obj);
      Py_DECREF(obj);
    }
  }
}

#endif

#ifdef __cplusplus
}
#endif








/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_Vector4 swig_types[0] 
#define  SWIGTYPE_p_Vector swig_types[1] 
#define  SWIGTYPE_p_Vector2 swig_types[2] 
static swig_type_info *swig_types[4];

/* -------- TYPES TABLE (END) -------- */


/*-----------------------------------------------
              @(target):= vectorc.so
  ------------------------------------------------*/
#define SWIG_init    initvectorc

#define SWIG_name    "vectorc"

 /* Put header files here (optional) */
#include "..\..\shared\vector.h"

 
#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_Vector2_x_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector2 *arg1 ;
    float arg2 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Of:Vector2_x_set",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector2,1)) == -1) return NULL;
    if (arg1) arg1->x = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_Vector2_x_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector2 *arg1 ;
    float result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Vector2_x_get",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector2,1)) == -1) return NULL;
    result = (float ) (arg1->x);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
}


static PyObject *_wrap_Vector2_y_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector2 *arg1 ;
    float arg2 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Of:Vector2_y_set",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector2,1)) == -1) return NULL;
    if (arg1) arg1->y = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_Vector2_y_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector2 *arg1 ;
    float result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Vector2_y_get",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector2,1)) == -1) return NULL;
    result = (float ) (arg1->y);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
}


static PyObject *_wrap_new_Vector2(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector2 *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_Vector2")) return NULL;
    result = (Vector2 *)new Vector2();
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Vector2, 1);
    return resultobj;
}


static PyObject *_wrap_Vector2_Average(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector2 *arg1 ;
    float result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Vector2_Average",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector2,1)) == -1) return NULL;
    result = (float )((Vector2 const *)arg1)->Average();
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
}


static PyObject *_wrap_Vector2___call__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector2 *arg1 ;
    float arg2 ;
    float arg3 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Off:Vector2___call__",&obj0,&arg2,&arg3)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector2,1)) == -1) return NULL;
    (arg1)->operator ()(arg2,arg3);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_Vector2___eq__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector2 *arg1 ;
    Vector2 *arg2 ;
    bool result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Vector2___eq__",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector2,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector2,1)) == -1) return NULL;
    result = (bool )((Vector2 const *)arg1)->operator ==((Vector2 const &)*arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_Vector2___imul__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector2 *arg1 ;
    float arg2 ;
    Vector2 *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Of:Vector2___imul__",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector2,1)) == -1) return NULL;
    Vector2 &_result_ref = (arg1)->operator *=(arg2);
    result = (Vector2 *) &_result_ref;
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Vector2, 0);
    return resultobj;
}


static PyObject *_wrap_delete_Vector2(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector2 *arg1 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_Vector2",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector2,1)) == -1) return NULL;
    delete arg1;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject * Vector2_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_Vector2, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyObject *_wrap_Vector_x_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    float arg2 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Of:Vector_x_set",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if (arg1) arg1->x = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_Vector_x_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    float result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Vector_x_get",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = (float ) (arg1->x);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
}


static PyObject *_wrap_Vector_y_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    float arg2 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Of:Vector_y_set",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if (arg1) arg1->y = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_Vector_y_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    float result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Vector_y_get",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = (float ) (arg1->y);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
}


static PyObject *_wrap_Vector_z_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    float arg2 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Of:Vector_z_set",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if (arg1) arg1->z = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_Vector_z_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    float result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Vector_z_get",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = (float ) (arg1->z);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
}


static PyObject *_wrap_new_Vector(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    float arg1 ;
    float arg2 ;
    float arg3 ;
    Vector *result;
    
    if(!PyArg_ParseTuple(args,(char *)"fff:new_Vector",&arg1,&arg2,&arg3)) return NULL;
    result = (Vector *)new Vector(arg1,arg2,arg3);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Vector, 1);
    return resultobj;
}


static PyObject *_wrap_Vector___xor__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    Vector *arg2 ;
    Vector result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Vector___xor__",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = ((Vector const *)arg1)->operator ^((Vector const &)*arg2);
    
    {
        Vector * resultptr;
        resultptr = new Vector (result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_Vector, 1);
    }
    return resultobj;
}


static PyObject *_wrap_Vector___or__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    Vector *arg2 ;
    float result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Vector___or__",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = (float )((Vector const *)arg1)->operator |((Vector const &)*arg2);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
}


static PyObject *_wrap_Vector___add__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    Vector *arg2 ;
    Vector result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Vector___add__",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = ((Vector const *)arg1)->operator +((Vector const &)*arg2);
    
    {
        Vector * resultptr;
        resultptr = new Vector (result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_Vector, 1);
    }
    return resultobj;
}


static PyObject *_wrap_Vector___sub__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    Vector *arg2 ;
    Vector result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Vector___sub__",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = ((Vector const *)arg1)->operator -((Vector const &)*arg2);
    
    {
        Vector * resultptr;
        resultptr = new Vector (result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_Vector, 1);
    }
    return resultobj;
}


static PyObject *_wrap_Vector___div__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    float arg2 ;
    Vector result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Of:Vector___div__",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = ((Vector const *)arg1)->operator /(arg2);
    
    {
        Vector * resultptr;
        resultptr = new Vector (result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_Vector, 1);
    }
    return resultobj;
}


static PyObject *_wrap_Vector___eq__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    Vector *arg2 ;
    bool result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Vector___eq__",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = (bool )((Vector const *)arg1)->operator ==((Vector const &)*arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_Vector___ne__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    Vector *arg2 ;
    bool result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Vector___ne__",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = (bool )((Vector const *)arg1)->operator !=((Vector const &)*arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_Vector___neg__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    Vector result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Vector___neg__",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = ((Vector const *)arg1)->operator -();
    
    {
        Vector * resultptr;
        resultptr = new Vector (result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_Vector, 1);
    }
    return resultobj;
}


static PyObject *_wrap_Vector___iadd__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    Vector *arg2 ;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Vector___iadd__",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    (arg1)->operator +=((Vector const &)*arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_Vector___isub__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    Vector *arg2 ;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Vector___isub__",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    (arg1)->operator -=((Vector const &)*arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_Vector___imul__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    float arg2 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Of:Vector___imul__",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    (arg1)->operator *=(arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_Vector___idiv__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    float arg2 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Of:Vector___idiv__",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    (arg1)->operator /=(arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_Vector_Length(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    float result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Vector_Length",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = (float )((Vector const *)arg1)->Length();
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
}


static PyObject *_wrap_Vector_IsNearlyZero(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Vector_IsNearlyZero",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = (int )((Vector const *)arg1)->IsNearlyZero();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_Vector_IsZero(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Vector_IsZero",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = (bool )((Vector const *)arg1)->IsZero();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_Vector_Normalize(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Vector_Normalize",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = (bool )(arg1)->Normalize();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_Vector_Set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    float arg2 ;
    float arg3 ;
    float arg4 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Offf:Vector_Set",&obj0,&arg2,&arg3,&arg4)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    (arg1)->Set(arg2,arg3,arg4);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_Vector_Add(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    Vector *arg2 ;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Vector_Add",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    (arg1)->Add(*arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_Vector_Sub(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    Vector *arg2 ;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Vector_Sub",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    (arg1)->Sub(*arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_Vector_Mul(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    Vector *arg2 ;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Vector_Mul",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    (arg1)->Mul(*arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_Vector_Cmp(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    Vector *arg2 ;
    bool result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Vector_Cmp",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = (bool )(arg1)->Cmp(*arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_Vector_MakeDirection(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    float arg1 ;
    float arg2 ;
    float arg3 ;
    Vector result;
    
    if(!PyArg_ParseTuple(args,(char *)"fff:Vector_MakeDirection",&arg1,&arg2,&arg3)) return NULL;
    result = Vector::MakeDirection(arg1,arg2,arg3);
    
    {
        Vector * resultptr;
        resultptr = new Vector (result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_Vector, 1);
    }
    return resultobj;
}


static PyObject *_wrap_Vector_NormalFromTriangle(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    Vector *arg2 ;
    Vector *arg3 ;
    Vector result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    PyObject * obj2  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOO:Vector_NormalFromTriangle",&obj0,&obj1,&obj2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = Vector::NormalFromTriangle((Vector const &)*arg1,(Vector const &)*arg2,(Vector const &)*arg3);
    
    {
        Vector * resultptr;
        resultptr = new Vector (result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_Vector, 1);
    }
    return resultobj;
}


static PyObject *_wrap_Vector_Yaw(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    double result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Vector_Yaw",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = (double )(arg1)->Yaw();
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
}


static PyObject *_wrap_Vector_Pitch(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    double result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Vector_Pitch",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = (double )(arg1)->Pitch();
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
}


static PyObject *_wrap_Vector_Roll(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    double result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Vector_Roll",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = (double )(arg1)->Roll();
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
}


static PyObject *_wrap_Vector_Zero(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Vector_Zero",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    (arg1)->Zero();
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_Vector_Normalized(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    Vector result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Vector_Normalized",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = ((Vector const *)arg1)->Normalized();
    
    {
        Vector * resultptr;
        resultptr = new Vector (result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_Vector, 1);
    }
    return resultobj;
}


static PyObject *_wrap_Vector_DotSelf(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    float result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Vector_DotSelf",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = (float )((Vector const *)arg1)->DotSelf();
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
}


static PyObject *_wrap_Vector_Dot(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    Vector *arg2 ;
    float result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Vector_Dot",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = (float )((Vector const *)arg1)->Dot((Vector const &)*arg2);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
}


static PyObject *_wrap_Vector_ScalarProjectionOntoVector(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    Vector *arg2 ;
    float result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Vector_ScalarProjectionOntoVector",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = (float )(arg1)->ScalarProjectionOntoVector(*arg2);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
}


static PyObject *_wrap_Vector_ProjectionOntoVector(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    Vector *arg2 ;
    Vector result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Vector_ProjectionOntoVector",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = (arg1)->ProjectionOntoVector((Vector const &)*arg2);
    
    {
        Vector * resultptr;
        resultptr = new Vector (result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_Vector, 1);
    }
    return resultobj;
}


static PyObject *_wrap_Vector_Lerp(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    Vector *arg2 ;
    float arg3 ;
    Vector result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOf:Vector_Lerp",&obj0,&obj1,&arg3)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = (arg1)->Lerp((Vector const &)*arg2,arg3);
    
    {
        Vector * resultptr;
        resultptr = new Vector (result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_Vector, 1);
    }
    return resultobj;
}


static PyObject *_wrap_Vector_RadAngle(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    Vector *arg2 ;
    float result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Vector_RadAngle",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = (float )((Vector const *)arg1)->RadAngle((Vector const &)*arg2);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
}


static PyObject *_wrap_Vector_CosAngle(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    Vector *arg2 ;
    float result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Vector_CosAngle",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = (float )((Vector const *)arg1)->CosAngle((Vector const &)*arg2);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
}


static PyObject *_wrap_Vector_Reflected(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    Vector *arg2 ;
    Vector result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Vector_Reflected",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = (arg1)->Reflected((Vector const &)*arg2);
    
    {
        Vector * resultptr;
        resultptr = new Vector (result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_Vector, 1);
    }
    return resultobj;
}


static PyObject *_wrap_Vector_DistanceToLine(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    Vector *arg2 ;
    Vector *arg3 ;
    float result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    PyObject * obj2  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOO:Vector_DistanceToLine",&obj0,&obj1,&obj2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = (float )((Vector const *)arg1)->DistanceToLine((Vector const &)*arg2,(Vector const &)*arg3);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
}


static PyObject *_wrap_Vector_Average(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    float result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Vector_Average",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = (float )((Vector const *)arg1)->Average();
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
}


static PyObject *_wrap_Vector_HalfWay(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    Vector *arg2 ;
    Vector result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Vector_HalfWay",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = ((Vector const *)arg1)->HalfWay((Vector const &)*arg2);
    
    {
        Vector * resultptr;
        resultptr = new Vector (result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_Vector, 1);
    }
    return resultobj;
}


static PyObject *_wrap_delete_Vector(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_Vector",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    delete arg1;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject * Vector_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_Vector, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyObject *_wrap_Cross(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector *arg1 ;
    Vector *arg2 ;
    Vector result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Cross",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector,1)) == -1) return NULL;
    result = Cross((Vector const &)*arg1,*arg2);
    
    {
        Vector * resultptr;
        resultptr = new Vector (result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_Vector, 1);
    }
    return resultobj;
}


static PyObject *_wrap_Vector4_w_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector4 *arg1 ;
    float arg2 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Of:Vector4_w_set",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector4,1)) == -1) return NULL;
    if (arg1) arg1->w = arg2;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_Vector4_w_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector4 *arg1 ;
    float result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Vector4_w_get",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector4,1)) == -1) return NULL;
    result = (float ) (arg1->w);
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
}


static PyObject *_wrap_new_Vector4(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector4 *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_Vector4")) return NULL;
    result = (Vector4 *)new Vector4();
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Vector4, 1);
    return resultobj;
}


static PyObject *_wrap_Vector4_Lerp(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector4 *arg1 ;
    Vector4 *arg2 ;
    float arg3 ;
    Vector4 result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOf:Vector4_Lerp",&obj0,&obj1,&arg3)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector4,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector4,1)) == -1) return NULL;
    result = (arg1)->Lerp((Vector4 const &)*arg2,arg3);
    
    {
        Vector4 * resultptr;
        resultptr = new Vector4 (result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_Vector4, 1);
    }
    return resultobj;
}


static PyObject *_wrap_Vector4___mul__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector4 *arg1 ;
    float arg2 ;
    Vector4 result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Of:Vector4___mul__",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector4,1)) == -1) return NULL;
    result = ((Vector4 const *)arg1)->operator *(arg2);
    
    {
        Vector4 * resultptr;
        resultptr = new Vector4 (result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_Vector4, 1);
    }
    return resultobj;
}


static PyObject *_wrap_Vector4___imul__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector4 *arg1 ;
    float arg2 ;
    Vector4 *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Of:Vector4___imul__",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector4,1)) == -1) return NULL;
    Vector4 &_result_ref = (arg1)->operator *=(arg2);
    result = (Vector4 *) &_result_ref;
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Vector4, 0);
    return resultobj;
}


static PyObject *_wrap_Vector4___add__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector4 *arg1 ;
    Vector4 *arg2 ;
    Vector4 result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Vector4___add__",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector4,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector4,1)) == -1) return NULL;
    result = ((Vector4 const *)arg1)->operator +((Vector4 const &)*arg2);
    
    {
        Vector4 * resultptr;
        resultptr = new Vector4 (result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_Vector4, 1);
    }
    return resultobj;
}


static PyObject *_wrap_Vector4___iadd__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector4 *arg1 ;
    Vector4 *arg2 ;
    Vector4 *result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Vector4___iadd__",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector4,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector4,1)) == -1) return NULL;
    Vector4 &_result_ref = (arg1)->operator +=((Vector4 const &)*arg2);
    result = (Vector4 *) &_result_ref;
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Vector4, 0);
    return resultobj;
}


static PyObject *_wrap_Vector4___sub__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector4 *arg1 ;
    Vector4 *arg2 ;
    Vector4 result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Vector4___sub__",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector4,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector4,1)) == -1) return NULL;
    result = ((Vector4 const *)arg1)->operator -((Vector4 const &)*arg2);
    
    {
        Vector4 * resultptr;
        resultptr = new Vector4 (result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_Vector4, 1);
    }
    return resultobj;
}


static PyObject *_wrap_Vector4___isub__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector4 *arg1 ;
    Vector4 *arg2 ;
    Vector4 *result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:Vector4___isub__",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector4,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_Vector4,1)) == -1) return NULL;
    Vector4 &_result_ref = (arg1)->operator -=((Vector4 const &)*arg2);
    result = (Vector4 *) &_result_ref;
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Vector4, 0);
    return resultobj;
}


static PyObject *_wrap_Vector4___div__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector4 *arg1 ;
    float arg2 ;
    Vector4 result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Of:Vector4___div__",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector4,1)) == -1) return NULL;
    result = ((Vector4 const *)arg1)->operator /(arg2);
    
    {
        Vector4 * resultptr;
        resultptr = new Vector4 (result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_Vector4, 1);
    }
    return resultobj;
}


static PyObject *_wrap_Vector4___idiv__(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector4 *arg1 ;
    float arg2 ;
    Vector4 *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Of:Vector4___idiv__",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector4,1)) == -1) return NULL;
    Vector4 &_result_ref = (arg1)->operator /=(arg2);
    result = (Vector4 *) &_result_ref;
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_Vector4, 0);
    return resultobj;
}


static PyObject *_wrap_Vector4_Length(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector4 *arg1 ;
    float result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Vector4_Length",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector4,1)) == -1) return NULL;
    result = (float )((Vector4 const *)arg1)->Length();
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
}


static PyObject *_wrap_Vector4_Average(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector4 *arg1 ;
    float result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Vector4_Average",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector4,1)) == -1) return NULL;
    result = (float )((Vector4 const *)arg1)->Average();
    
    resultobj = PyFloat_FromDouble(result);
    return resultobj;
}


static PyObject *_wrap_Vector4_Normalized(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector4 *arg1 ;
    Vector4 result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:Vector4_Normalized",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector4,1)) == -1) return NULL;
    result = ((Vector4 const *)arg1)->Normalized();
    
    {
        Vector4 * resultptr;
        resultptr = new Vector4 (result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_Vector4, 1);
    }
    return resultobj;
}


static PyObject *_wrap_delete_Vector4(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    Vector4 *arg1 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_Vector4",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_Vector4,1)) == -1) return NULL;
    delete arg1;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject * Vector4_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_Vector4, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyMethodDef SwigMethods[] = {
	 { (char *)"Vector2_x_set", _wrap_Vector2_x_set, METH_VARARGS },
	 { (char *)"Vector2_x_get", _wrap_Vector2_x_get, METH_VARARGS },
	 { (char *)"Vector2_y_set", _wrap_Vector2_y_set, METH_VARARGS },
	 { (char *)"Vector2_y_get", _wrap_Vector2_y_get, METH_VARARGS },
	 { (char *)"new_Vector2", _wrap_new_Vector2, METH_VARARGS },
	 { (char *)"Vector2_Average", _wrap_Vector2_Average, METH_VARARGS },
	 { (char *)"Vector2___call__", _wrap_Vector2___call__, METH_VARARGS },
	 { (char *)"Vector2___eq__", _wrap_Vector2___eq__, METH_VARARGS },
	 { (char *)"Vector2___imul__", _wrap_Vector2___imul__, METH_VARARGS },
	 { (char *)"delete_Vector2", _wrap_delete_Vector2, METH_VARARGS },
	 { (char *)"Vector2_swigregister", Vector2_swigregister, METH_VARARGS },
	 { (char *)"Vector_x_set", _wrap_Vector_x_set, METH_VARARGS },
	 { (char *)"Vector_x_get", _wrap_Vector_x_get, METH_VARARGS },
	 { (char *)"Vector_y_set", _wrap_Vector_y_set, METH_VARARGS },
	 { (char *)"Vector_y_get", _wrap_Vector_y_get, METH_VARARGS },
	 { (char *)"Vector_z_set", _wrap_Vector_z_set, METH_VARARGS },
	 { (char *)"Vector_z_get", _wrap_Vector_z_get, METH_VARARGS },
	 { (char *)"new_Vector", _wrap_new_Vector, METH_VARARGS },
	 { (char *)"Vector___xor__", _wrap_Vector___xor__, METH_VARARGS },
	 { (char *)"Vector___or__", _wrap_Vector___or__, METH_VARARGS },
	 { (char *)"Vector___add__", _wrap_Vector___add__, METH_VARARGS },
	 { (char *)"Vector___sub__", _wrap_Vector___sub__, METH_VARARGS },
	 { (char *)"Vector___div__", _wrap_Vector___div__, METH_VARARGS },
	 { (char *)"Vector___eq__", _wrap_Vector___eq__, METH_VARARGS },
	 { (char *)"Vector___ne__", _wrap_Vector___ne__, METH_VARARGS },
	 { (char *)"Vector___neg__", _wrap_Vector___neg__, METH_VARARGS },
	 { (char *)"Vector___iadd__", _wrap_Vector___iadd__, METH_VARARGS },
	 { (char *)"Vector___isub__", _wrap_Vector___isub__, METH_VARARGS },
	 { (char *)"Vector___imul__", _wrap_Vector___imul__, METH_VARARGS },
	 { (char *)"Vector___idiv__", _wrap_Vector___idiv__, METH_VARARGS },
	 { (char *)"Vector_Length", _wrap_Vector_Length, METH_VARARGS },
	 { (char *)"Vector_IsNearlyZero", _wrap_Vector_IsNearlyZero, METH_VARARGS },
	 { (char *)"Vector_IsZero", _wrap_Vector_IsZero, METH_VARARGS },
	 { (char *)"Vector_Normalize", _wrap_Vector_Normalize, METH_VARARGS },
	 { (char *)"Vector_Set", _wrap_Vector_Set, METH_VARARGS },
	 { (char *)"Vector_Add", _wrap_Vector_Add, METH_VARARGS },
	 { (char *)"Vector_Sub", _wrap_Vector_Sub, METH_VARARGS },
	 { (char *)"Vector_Mul", _wrap_Vector_Mul, METH_VARARGS },
	 { (char *)"Vector_Cmp", _wrap_Vector_Cmp, METH_VARARGS },
	 { (char *)"Vector_MakeDirection", _wrap_Vector_MakeDirection, METH_VARARGS },
	 { (char *)"Vector_NormalFromTriangle", _wrap_Vector_NormalFromTriangle, METH_VARARGS },
	 { (char *)"Vector_Yaw", _wrap_Vector_Yaw, METH_VARARGS },
	 { (char *)"Vector_Pitch", _wrap_Vector_Pitch, METH_VARARGS },
	 { (char *)"Vector_Roll", _wrap_Vector_Roll, METH_VARARGS },
	 { (char *)"Vector_Zero", _wrap_Vector_Zero, METH_VARARGS },
	 { (char *)"Vector_Normalized", _wrap_Vector_Normalized, METH_VARARGS },
	 { (char *)"Vector_DotSelf", _wrap_Vector_DotSelf, METH_VARARGS },
	 { (char *)"Vector_Dot", _wrap_Vector_Dot, METH_VARARGS },
	 { (char *)"Vector_ScalarProjectionOntoVector", _wrap_Vector_ScalarProjectionOntoVector, METH_VARARGS },
	 { (char *)"Vector_ProjectionOntoVector", _wrap_Vector_ProjectionOntoVector, METH_VARARGS },
	 { (char *)"Vector_Lerp", _wrap_Vector_Lerp, METH_VARARGS },
	 { (char *)"Vector_RadAngle", _wrap_Vector_RadAngle, METH_VARARGS },
	 { (char *)"Vector_CosAngle", _wrap_Vector_CosAngle, METH_VARARGS },
	 { (char *)"Vector_Reflected", _wrap_Vector_Reflected, METH_VARARGS },
	 { (char *)"Vector_DistanceToLine", _wrap_Vector_DistanceToLine, METH_VARARGS },
	 { (char *)"Vector_Average", _wrap_Vector_Average, METH_VARARGS },
	 { (char *)"Vector_HalfWay", _wrap_Vector_HalfWay, METH_VARARGS },
	 { (char *)"delete_Vector", _wrap_delete_Vector, METH_VARARGS },
	 { (char *)"Vector_swigregister", Vector_swigregister, METH_VARARGS },
	 { (char *)"Cross", _wrap_Cross, METH_VARARGS },
	 { (char *)"Vector4_w_set", _wrap_Vector4_w_set, METH_VARARGS },
	 { (char *)"Vector4_w_get", _wrap_Vector4_w_get, METH_VARARGS },
	 { (char *)"new_Vector4", _wrap_new_Vector4, METH_VARARGS },
	 { (char *)"Vector4_Lerp", _wrap_Vector4_Lerp, METH_VARARGS },
	 { (char *)"Vector4___mul__", _wrap_Vector4___mul__, METH_VARARGS },
	 { (char *)"Vector4___imul__", _wrap_Vector4___imul__, METH_VARARGS },
	 { (char *)"Vector4___add__", _wrap_Vector4___add__, METH_VARARGS },
	 { (char *)"Vector4___iadd__", _wrap_Vector4___iadd__, METH_VARARGS },
	 { (char *)"Vector4___sub__", _wrap_Vector4___sub__, METH_VARARGS },
	 { (char *)"Vector4___isub__", _wrap_Vector4___isub__, METH_VARARGS },
	 { (char *)"Vector4___div__", _wrap_Vector4___div__, METH_VARARGS },
	 { (char *)"Vector4___idiv__", _wrap_Vector4___idiv__, METH_VARARGS },
	 { (char *)"Vector4_Length", _wrap_Vector4_Length, METH_VARARGS },
	 { (char *)"Vector4_Average", _wrap_Vector4_Average, METH_VARARGS },
	 { (char *)"Vector4_Normalized", _wrap_Vector4_Normalized, METH_VARARGS },
	 { (char *)"delete_Vector4", _wrap_delete_Vector4, METH_VARARGS },
	 { (char *)"Vector4_swigregister", Vector4_swigregister, METH_VARARGS },
	 { NULL, NULL }
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static void *_p_Vector4To_p_Vector(void *x) {
    return (void *)((Vector *) ((Vector4 *) x));
}
static swig_type_info _swigt__p_Vector4[] = {{"_p_Vector4", 0, "Vector4 *"},{"_p_Vector4"},{0}};
static swig_type_info _swigt__p_Vector[] = {{"_p_Vector", 0, "Vector *"},{"_p_Vector4", _p_Vector4To_p_Vector},{"_p_Vector"},{0}};
static swig_type_info _swigt__p_Vector2[] = {{"_p_Vector2", 0, "Vector2 *"},{"_p_Vector2"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_Vector4, 
_swigt__p_Vector, 
_swigt__p_Vector2, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_const_info swig_const_table[] = {
{ SWIG_PY_FLOAT,   (char*)"PI", 0, (double) (3.1415926535897932f), 0, 0},
{ SWIG_PY_FLOAT,   (char*)"SMALL_NUMBER", 0, (double) (1.e-8f), 0, 0},
{ SWIG_PY_FLOAT,   (char*)"KINDA_SMALL_NUMBER", 0, (double) (1.e-4f), 0, 0},
{ SWIG_PY_FLOAT,   (char*)"BIG_NUMBER", 0, (double) (1.0e+10f), 0, 0},
{0}};

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT(void) SWIG_init(void) {
    static PyObject *SWIG_globals = 0; 
    static int       typeinit = 0;
    PyObject *m, *d;
    int       i;
    if (!SWIG_globals) SWIG_globals = SWIG_newvarlink();
    m = Py_InitModule((char *) SWIG_name, SwigMethods);
    d = PyModule_GetDict(m);
    
    if (!typeinit) {
        for (i = 0; swig_types_initial[i]; i++) {
            swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
        }
        typeinit = 1;
    }
    SWIG_InstallConstants(d,swig_const_table);
    
}

