/*********************************************************************NVMH4****
Path:  NVSDK\Common\include\nv_renderdevice
File:  invrenderdevice_d3d.h

Copyright NVIDIA Corporation 2002
TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THIS SOFTWARE IS PROVIDED
*AS IS* AND NVIDIA AND ITS SUPPLIERS DISCLAIM ALL WARRANTIES, EITHER EXPRESS
OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS FOR A PARTICULAR PURPOSE.  IN NO EVENT SHALL NVIDIA OR ITS SUPPLIERS
BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT, OR CONSEQUENTIAL DAMAGES
WHATSOEVER (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS,
BUSINESS INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR ANY OTHER PECUNIARY LOSS)
ARISING OUT OF THE USE OF OR INABILITY TO USE THIS SOFTWARE, EVEN IF NVIDIA HAS
BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.



Comments:

INVRenderDevice_d3d9.


******************************************************************************/

#ifndef __INVRENDERDEVICE_D3D9_H
#define __INVRENDERDEVICE_D3D9_H

struct IDirect3DDevice9;
namespace nv_renderdevice
{
class INVRenderDevice_D3D9 : public INVRenderDevice
{
public:
	// INVRenderDevice_D3D9
	virtual bool INTCALLTYPE GetDevice(IDirect3DDevice9** pDevice) = 0;
};

};

// {3989C7F5-1DA9-4c8a-94D6-F7796B0DF58F}
static const nv_sys::NVGUID IID_INVRenderDevice_D3D9 = 
{ 0x3989c7f5, 0x1da9, 0x4c8a, { 0x94, 0xd6, 0xf7, 0x79, 0x6b, 0xd, 0xf5, 0x8f } };

#endif //__INVRENDERDEVICE_D3D9_H