//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MaxPlugin.rc
//
#define IDS_NAME                        1
#define IDS_VALUE                       2
#define IDS_TYPE                        3
#define IDS_LIBDESC                     4
#define IDS_LIBDESCRIPTION              4
#define IDS_CLASSNAME                   5
#define IDS_PARAMETERS                  6
#define IDS_AUTHOR                      7
#define IDS_PROPTEXT                    7
#define IDS_ACTION1_DESC                7
#define IDS_PROPNUMBER                  8
#define IDS_ACTION2_DESC                8
#define IDS_PROPYESNO                   9
#define IDS_ACTION3_DESC                9
#define IDS_PROPDATE                    10
#define IDS_ACTION4_DESC                10
#define IDS_PROPYES                     11
#define IDS_ACTION5_DESC                11
#define IDS_PROPNO                      12
#define IDS_FPACTIONS_CATEGORY          12
#define IDS_CLASS_NAME                  13
#define IDS_CLASS_CATEGORY              14
#define IDS_ACTION6_DESC                15
#define IDS_ACTION7_DESC                16
#define IDS_ACTION8_DESC                17
#define IDS_CLASS_CATEGORY2             18
#define IDS_ERR1                        19
#define IDS_ERRTITLE                    20
#define IDS_ERR2                        21
#define IDS_ERR3                        22
#define IDS_ACTION9_DESC                23
#define IDD_PANEL                       101
#define IDC_CLOSEBUTTON                 1000
#define IDC_SHOWPROP                    1001
#define IDC_BROWSE_UNCOMPILED           1001
#define IDC_CONTENTS                    1002
#define IDC_SAVEANDCOMPILE              1002
#define IDC_SAVE                        1003
#define IDC_LIST_NODES                  1003
#define IDC_CUSTOM                      1004
#define IDC_BROWSE_COMPILED             1004
#define IDC_BROWSE_ANIMATION            1005
#define IDC_UNCOMPILED_PATH             1006
#define IDC_COMPILED_PATH               1007
#define IDC_CHK_PROXY                   1007
#define IDC_MODEL_FILENAME              1008
#define IDC_CHK_NOANIM                  1008
#define IDC_ANIMATIONMANAGER            1009
#define IDC_BROWSEFORCOMPILER           1010
#define IDC_SAVESELECTED                1011
#define IDC_SAVESELECTED_MODEL          1011
#define IDC_EDIT_EXPRES                 1011
#define IDC_ANIMATION_PATH              1012
#define IDC_TEST                        1013
#define IDC_TITLE                       1014
#define IDC_ANIMATION_FILENAME          1014
#define IDC_SUBJECT                     1015
#define IDC_SAVEANIMATION               1015
#define IDC_AUTHOR                      1016
#define IDC_CHECK1                      1016
#define IDC_ISLOOPING                   1016
#define IDC_MANAGER                     1017
#define IDC_SAVESELECTED_ANIMATION      1017
#define IDC_COMPANY                     1018
#define IDC_BROWSE_UNCOMPILED2          1018
#define IDC_CATEGORY                    1019
#define IDC_SAVEANDCOMPILE2             1019
#define IDC_KEYWORDS                    1020
#define IDC_SAVE2                       1020
#define IDC_SAVELEVEL                   1020
#define IDC_COMMENTS                    1021
#define IDC_BROWSE_COMPILED2            1021
#define IDC_INFO                        1021
#define IDC_UNCOMPILED_PATH2            1022
#define IDC_COMPILED_PATH2              1023
#define IDC_LEVEL_FILENAME              1024
#define IDC_BROWSEFORGAME               1025
#define IDC_SAVESELECTED2               1026
#define IDC_SAVESELECTED_LEVEL          1026
#define IDC_COMPILER_LOCATION           1027
#define IDC_SKYBOX                      1027
#define IDC_GAME_LOCATION               1028
#define IDC_BROWSE_SKYBOX               1028
#define IDC_CLIPPLANE                   1029
#define IDC_SAVEMODEL                   1029
#define IDC_FOGSTART                    1030
#define IDC_MINIMAP                     1031
#define IDC_BROWSE_MINIMAP              1032
#define IDC_TEXT                        1035
#define IDC_ADD                         1035
#define IDC_BINARY                      1036
#define IDC_FILES                       1036
#define IDC_BINARYCOMPRESSED            1037
#define IDC_PATCHDATA                   1038
#define IDC_FOLDERS                     1038
#define IDC_ANIMATION                   1039
#define IDC_SAMPLERATE                  1040
#define IDC_LOOPINGANIMATION            1041
#define IDC_MAX_BONES_PER_VERTEX        1042
#define IDC_COLOR_SWATCH                1042
#define IDC_PATH                        1042
#define IDC_MAX_BONES_PER_FACE          1043
#define IDC_LISTVIEW                    1044
#define IDC_SCENEDESC                   1047
#define IDC_BUTTON1                     1048
#define IDC_SAVEASPREFAB                1048
#define IDC_SPAWNENTITY                 1048
#define IDC_CLASSINFO                   1050
#define IDC_SAVEASPREFAB2               1050
#define IDC_SAVETOMAX                   1050
#define IDC_SCENEINFO                   1051
#define IDC_LINK                        1052
#define IDC_LINK2                       1053
#define IDC_EMAIL                       1053
#define IDC_MINIMAP_SCALE               1054
#define IDC_FOGVALUE                    1055
#define IDC_CLIPVALUE                   1056
#define IDC_EDITSCRIPT                  1112
#define IDC_APPDATA_CLASSES             1114
#define IDC_SETSCRIPTFOLDER             1115
#define IDC_REFRESHSCRIPTS              1120

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        117
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1056
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
