//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by gui.rc
//
#define IDS_NAME                        1
#define IDS_VALUE                       2
#define IDS_TYPE                        3
#define IDC_ADAPTIVE_SETTINGS           3
#define IDS_LIBDESCRIPTION              4
#define IDI_OPEN                        5
#define IDS_PARAMETERS                  6
#define IDS_ACTION1_DESC                7
#define IDS_ACTION2_DESC                8
#define IDS_ACTION3_DESC                9
#define IDS_ACTION4_DESC                10
#define IDS_ACTION5_DESC                11
#define IDS_FPACTIONS_CATEGORY          12
#define IDS_CLASS_NAME                  13
#define IDS_CLASS_CATEGORY              14
#define IDS_ACTION6_DESC                15
#define IDS_ACTION7_DESC                16
#define IDS_ACTION8_DESC                17
#define IDS_ERR1                        19
#define IDS_ERRTITLE                    20
#define IDS_ERR2                        21
#define IDS_ERR3                        22
#define IDS_ACTION9_DESC                23
#define IDS_PARAMS                      24
#define IDS_SPIN                        25
#define IDS_COORDS                      26
#define IDS_PSCATEGORY                  27
#define IDS_VSCATEGORY                  28
#define IDS_VSCLASS_NAME                29
#define IDS_VSPARAMS                    30
#define IDS_BPSCLASS_NAME               31
#define IDS_MAPFILENAME                 32
#define IDS_VSFILENAME                  33
#define IDS_TEXTURE_TYPES               34
#define IDS_MAT_STATE                   35
#define IDS_BUTTON                      36
#define IDS_COLOR                       37
#define IDS_UV                          38
#define IDS_BUMP_SCALE                  39
#define IDS_TEX_SCALE                   40
#define IDS_COLOR_AMB                   41
#define IDS_COLOR_DIFF                  42
#define IDS_COLOR_SPEC                  43
#define IDS_ALPHA                       44
#define IDS_ACTION10_DESC               45
#define IDS_CLASS_NAME2                 46
#define IDS_CATEGORY                    47
#define IDS_MAP_DIFFUSE1                48
#define IDS_MAP_DIFFUSE2                49
#define IDS_MAP_SPECULAR                50
#define IDS_MAP_BUMP                    51
#define IDS_SYNC                        52
#define IDS_ACUBIC_NAME                 53
#define IDS_SELECT_CUBIC                54
#define IDS_BITMAP_NONE                 55
#define IDS_DDS_FILTER_NAME             56
#define IDS_DDS_FILTER_DESC             57
#define IDS_FILE_REPLACE                58
#define IDS_SAVE_AS                     59
#define IDS_MIX_SCALE                   60
#define IDS_REFLECT_SCALE               61
#define IDS_CGFX                        62
#define IDS_TECHNIQUE                   63
#define IDS_CONNECTIONS                 64
#define IDS_DYNMATFLOAT_DATA            65
#define IDS_DYNMATFILENAME_DATA         66
#define IDS_DYNMATINT_DATA              67
#define IDS_SYNC_DIFFUSE                68
#define IDS_SYNC_SPECULAR               69
#define IDS_SYNC_BUMP                   70
#define IDS_SYNC_AMBIENT                71
#define IDS_SYNC_GLOSS                  72
#define IDS_SYNC_SELFILLUMINATION       73
#define IDS_SYNC_OPACITY                74
#define IDS_SYNC_FILTERCOLOR            75
#define IDS_SYNC_REFLECTION             76
#define IDS_SYNC_REFRACTION             77
#define IDS_SYNC_DISPLACEMENT           78
#define IDS_TECHNIQUENAME               79
#define IDD_PANEL                       101
#define IDD_PICKOBJ                     102
#define IDD_DLGEXPORT                   103
#define IDD_MAX_SHADER                  104
#define IDB_BITMAP1                     107
#define IDD_OBJECT_PROPERTIES           108
#define IDD_MAPSETTINGS                 109
#define IDD_PREFABS                     110
#define IDI_EDIT                        114
#define IDI_REFRESH                     115
#define IDD_HELP                        116
#define IDR_CGFXTYPE                    129
#define IDR_CGFXTYPE1                   130
#define IDC_SPLITTER                    157
#define IDC_FPOINT                      158
#define IDB_TWEAKABLE_TYPES_MASK        201
#define IDB_TWEAKABLE_TYPES             202
#define IDB_TWEAKABLE_TYPES_DISABLED    203
#define IDC_LISTBOX                     1000
#define IDD_DEBUGDLG                    1000
#define IDC_BROWSE_UNCOMPILED           1001
#define IDC_ENABLE_ROBUST_MESH_REFINE   1001
#define IDC_SAVEANDCOMPILE              1002
#define IDC_RMR_MIN_EDGE_TEXT           1002
#define IDC_LIST_NODES                  1003
#define IDC_RMR_MIN_EDGE_EDIT           1003
#define IDC_BROWSE_COMPILED             1004
#define IDC_RMR_MAX_SUBD_SPIN           1004
#define IDC_BROWSE_ANIMATION            1005
#define IDC_UNCOMPILED_PATH             1006
#define IDC_CHK_PROXY                   1007
#define IDC_COMPILED_PATH               1007
#define IDC_CHK_NOANIM                  1008
#define IDC_MODEL_FILENAME              1008
#define IDC_EDITCONNECTIONS             1008
#define IDC_BROWSEFORCOMPILER           1010
#define IDC_SAVESELECTED_MODEL          1011
#define IDC_EDIT_EXPRES                 1011
#define IDC_ANIMATION_PATH              1012
#define IDC_TEST                        1013
#define IDC_SYNC_DIFFUSE                1013
#define IDC_ANIMATION_FILENAME          1014
#define IDC_SYNC_SPECULAR               1014
#define IDC_SAVEANIMATION               1015
#define IDC_SYNC_BUMP                   1015
#define IDC_ISLOOPING                   1016
#define IDC_SYNC_GLOSS                  1016
#define IDC_SAVESELECTED_ANIMATION      1017
#define IDC_SYNC_SELFILLUMINATION       1017
#define IDC_BROWSE_UNCOMPILED2          1018
#define IDC_SYNC_OPACITY                1018
#define IDC_SAVEANDCOMPILE2             1019
#define IDC_SYNC_FILTERCOLOR            1019
#define IDC_SAVELEVEL                   1020
#define IDC_SYNC_AMBIENT                1020
#define IDC_INFO                        1021
#define IDC_COMMENTS                    1021
#define IDC_BROWSE_COMPILED2            1021
#define IDC_CGFXFILE                    1021
#define IDC_UNCOMPILED_PATH2            1022
#define IDC_SYNC_REFLECTION             1022
#define IDC_COMPILED_PATH2              1023
#define IDC_SYNC_REFRACTION             1023
#define IDC_LEVEL_FILENAME              1024
#define IDC_SYNC_DISPLACEMENT           1024
#define IDC_BROWSEFORGAME               1025
#define IDC_SAVESELECTED_LEVEL          1026
#define IDC_SKYBOX                      1027
#define IDC_COMPILER_LOCATION           1027
#define IDC_BROWSE_SKYBOX               1028
#define IDC_GAME_LOCATION               1028
#define IDC_CLIPPLANE                   1029
#define IDC_SAVEMODEL                   1029
#define IDC_FOGSTART                    1030
#define IDC_MINIMAP                     1031
#define IDC_BROWSE_MINIMAP              1032
#define IDC_SH_CUBEMAP                  1033
#define IDC_BROWSE_MINIMAP2             1034
#define IDC_ADD                         1035
#define IDC_TEXT                        1035
#define IDC_FILES                       1036
#define IDC_BROWSE_CUBEMAP              1036
#define IDC_BINARYCOMPRESSED            1037
#define IDC_FOLDERS                     1038
#define IDC_SAMPLERATE                  1040
#define IDC_PATH                        1042
#define IDC_COLOR_SWATCH                1042
#define IDC_LISTVIEW                    1044
#define IDC_SCENEDESC                   1047
#define IDC_SAVEASPREFAB                1048
#define IDC_SPAWNENTITY                 1048
#define IDC_SAVETOMAX                   1050
#define IDC_SCENEINFO                   1051
#define IDC_LINK                        1052
#define IDC_EMAIL                       1053
#define IDC_MINIMAP_SCALE               1054
#define IDC_FOGVALUE                    1055
#define IDC_CLIPVALUE                   1056
#define IDC_EDITSCRIPT                  1112
#define IDC_APPDATA_CLASSES             1114
#define IDC_SETSCRIPTFOLDER             1115
#define IDC_REFRESHSCRIPTS              1120
#define IDC_HELP                        1526
#define IDC_ABOUT                       1527
#define IDB_BITMAP_HSB                  2000
#define IDC_NUM_BOUNCES_EDIT            2000
#define IDB_BITMAP_RGB                  2001
#define IDC_NUM_BOUNCES_SPIN            2001
#define IDC_ORDER_SLIDER                2002
#define IDC_SPIN1                       2003
#define IDS_NOITEMSEL                   2003
#define IDS_FALSE                       2004
#define IDI_CONNECTION                  2004
#define IDC_NUM_RAYS_EDIT               2004
#define IDS_TRUE                        2005
#define IDC_NUM_RAYS_SPIN               2005
#define IDS_SELFORINFO                  2006
#define IDR_CONNECTION_EDITOR_OPTIONS   2006
#define IDC_RMR_MAX_SUBD_EDIT           2006
#define IDC_PROPERTYTREE                2007
#define IDC_DL_MIN_EDGE_EDIT            2007
#define IDC_BITMAP_PREVIEW              2008
#define IDC_SPECTRAL_CHECK              2008
#define IDC_DL_SUBD_THRESHOLD_EDIT      2008
#define IDB_CGFX_TOOLBAR_DISABLED       2009
#define IDC_BITMAP_WIDTH                2009
#define IDC_DL_MAX_SUBD_SPIN            2009
#define IDB_CGFX_TOOLBAR                2010
#define IDC_BITMAP_HEIGHT               2010
#define IDC_INBLOCKERS                  2010
#define IDC_DL_MAX_SUBD_EDIT            2010
#define IDC_BITMAP_FORMAT               2011
#define IDC_OUTBLOCKERS                 2011
#define IDC_BITMAP_DEPTH                2012
#define IDC_ADDINBLOCKER                2012
#define IDC_BITMAP_COMPRESSION          2013
#define IDC_ADDOUTBLOCKER               2013
#define IDC_RMR_MAX_SUBD_TEXT           2013
#define IDC_BITMAP_CUBE                 2014
#define IDC_REMOVEIN                    2014
#define IDC_DL_MIN_EDGE_TEXT            2014
#define IDC_BITMAP_NUM_MIPMAPS          2015
#define IDC_REMOVEOUT                   2015
#define IDC_ENABLE_ADAPTIVE_DIRECT_LIGHTING 2015
#define IDC_BITMAP_BITS_PER_PIXEL       2016
#define IDC_NUM_RAYS_TEXT               2016
#define IDC_DL_MAX_SUBD_TEXT            2016
#define IDR_CGFXMENU                    2017
#define IDC_SUBSURF_CHECK               2017
#define IDC_DL_SUBD_THRESHOLD_TEXT      2017
#define IDD_BITMAP_PREVIEW_DLG          2018
#define IDC_PREDEF_TEXT                 2018
#define IDC_AB_MIN_EDGE_EDIT            2018
#define IDB_DEFAULT                     2019
#define IDC_PREDEF_COMBO                2019
#define IDC_AB_MAX_SUBD_SPIN            2019
#define IDC_REFRACTION_TEXT             2020
#define IDC_ENABLE_ADAPTIVE_BOUNCE      2020
#define IDB_DEFAULT_SMALL               2021
#define IDC_REFRACTION_EDIT             2021
#define IDC_AB_MAX_SUBD_TEXT            2021
#define IDD_EXPORT                      2022
#define IDC_AB_MAX_SUBD_EDIT            2022
#define IDC_AB_SUBD_THRESHOLD_TEXT      2023
#define IDD_ADAPTIVE_OPTIONS            2023
#define IDC_AB_SUBD_THRESHOLD_EDIT      2024
#define IDC_SHINFO                      2025
#define IDC_ENABLESH                    2026
#define IDC_AB_MIN_EDGE_TEXT            2026
#define IDC_REFLECTANCE_R_EDIT          2027
#define IDC_REFLECTANCE_G_EDIT          2028
#define IDC_REFLECTANCE_B_EDIT          2029
#define IDC_ORDER_TEXT                  2030
#define IDC_NUM_BOUNCES_TEXT            2031
#define IDC_SCATTERING_TEXT             2032
#define IDC_PRT_SETTINGS_TEXT           2033
#define IDC_MATERIAL_SETTINGS_TEXT      2034
#define IDC_PRT_SETTINGS_TEXT2          2034
#define IDC_PRT_SETTINGS_TEXT3          2035
#define IDC_PERPIXEL                    2035
#define IDC_REFLECTANCE_TEXT            2036
#define IDC_RED_TEXT                    2037
#define IDC_GREEN_TEXT                  2038
#define IDC_BLUE_TEXT                   2039
#define IDC_SCATTERING_R_EDIT           2040
#define IDC_ADAPTIVE_CHECK              2041
#define IDC_SCATTERING_G_EDIT           2042
#define IDC_SCATTERING_B_EDIT           2043
#define IDC_ABSORPTION_TEXT             2044
#define IDC_ABSORPTION_R_EDIT           2045
#define IDC_ABSORPTION_G_EDIT           2046
#define IDC_ABSORPTION_B_EDIT           2047
#define IDC_USECUSTOM                   2048
#define IDC_GLOBALOVERRIDE              2049
#define IDC_LENGTH_SCALE_EDIT           2050
#define IDC_PER_RAYS_EDIT               2050
#define IDC_LENGTH_SCALE_TEXT           2051
#define IDC_PER_BOUNCES_EDIT            2051
#define IDC_TEXTURE_SIZE_TEXT           2052
#define IDC_PER_RAYS_SPIN               2053
#define IDC_PER_BOUNCES_SPIN            2054
#define IDC_TEXTURE_SIZE_COMBO          2057
#define IDC_TEXTURE_PERCENT_COMBO       2058
#define IDC_STRIPSCENE                  2059
#define IDC_EDIT_DEFAULTS               2060
#define IDC_RELOAD_DEFAULTS             2061
#define IDC_BUTTON1                     2062
#define IDC_SELECTALL                   2062
#define IDD_DIALOG_COLORS               8000
#define IDD_TWEAKABLEPANE               8001
#define IDD_GRID                        8001
#define IDD_SH                          8002
#define IDC_STATIC_RGB_RECT             8100
#define IDC_STATIC_HSB_RECT             8101
#define IDC_EDIT_RED                    8102
#define IDC_SPIN_RED                    8103
#define IDC_EDIT_GREEN                  8104
#define IDC_SPIN_GREEN                  8105
#define IDC_EDIT_BLUE                   8106
#define IDC_SPIN_BLUE                   8107
#define IDC_STATIC_OLD                  8108
#define IDC_STATIC_NEW                  8109
#define IDC_EDIT_HUE                    8110
#define IDC_SPIN_HUE                    8111
#define IDC_EDIT_SAT                    8112
#define IDC_SPIN_SAT                    8113
#define IDC_EDIT_VAL                    8114
#define IDC_SPIN_VAL                    8115
#define IDC_READONLYATTRIBUTES          8116
#define IDD_EDIT_FIND                   8601
#define IDD_EDIT_REPLACE                8602
#define IDC_EDIT_WHOLE_WORD             8603
#define IDC_EDIT_MATCH_CASE             8604
#define IDC_EDIT_TEXT                   8605
#define IDS_EDIT_TEXT_NOT_FOUND         8606
#define IDC_EDIT_REPLACE                8607
#define IDC_EDIT_REPLACE_ALL            8608
#define IDC_EDIT_REPLACE_WITH           8609
#define IDC_EDIT_SKIP                   8610
#define IDC_EDIT_DIRECTION_UP           8611
#define IDC_EDIT_DIRECTION_DOWN         8612
#define IDC_EDIT_SCOPE_SELECTION        8613
#define IDC_EDIT_SCOPE_WHOLE_FILE       8614
#define IDS_MENU_UNDO_FORMAT            8615
#define IDS_MENU_REDO_FORMAT            8616
#define IDS_MENU_UNDO_DEFAULT           8617
#define IDS_MENU_REDO_DEFAULT           8618
#define IDS_EDITOP_UNKNOWN              8619
#define IDS_EDITOP_PASTE                8620
#define IDS_EDITOP_DELSELECTION         8621
#define IDS_EDITOP_CUT                  8622
#define IDS_EDITOP_DELETE               8623
#define IDS_EDITOP_TYPING               8624
#define IDS_EDITOP_BACKSPACE            8625
#define IDS_EDITOP_INDENT               8626
#define IDS_EDITOP_DRAGDROP             8627
#define IDS_EDITOP_REPLACE              8628
#define IDS_EDITOP_AUTOINDENT           8629
#define IDR_CGFXMAINFRAME               8630
#define IDR_MARGIN_CURSOR               22900
#define IDR_DEFAULT_ACCEL               22901
#define IDR_MARGIN_ICONS                22902
#define IDM_RENDER_FILLMODE_SOLID       32771
#define IDM_RENDER_FILLMODE_WIREFRAME   32772
#define IDM_RENDER_FILLMODE_POINT       32773
#define IDM_RENDER_OPTIONS_SHOWNORMALS  32774
#define IDM_RENDER_OPTIONS_LARGERNORMALS 32777
#define IDM_RENDER_OPTIONS_SMALLERNORMALS 32778
#define ID_VIEW_FULL_SCREEN             32791
#define ID_READ_ONLY                    32795
#define ID_EDIT_DISABLEBSATSOL          32796
#define ID_EDIT_DISABLEDRAGANDDROP      32797
#define ID_CHAR_BOLD                    32799
#define ID_CHAR_ITALIC                  32802
#define ID_CHAR_UNDERLINE               32804
#define ID_PARA_LEFT                    32805
#define ID_PARA_CENTER                  32806
#define ID_PARA_RIGHT                   32807
#define IDM_VIEW_BOUNDINGBOXES          32810
#define IDM_VIEW_SHOWLIGHTS             32811
#define IDM_VIEW_CAMERA                 32812
#define IDM_VIEW_DEBUGCONSOLE           32813
#define IDM_ANIMATION_NEXTFRAME         32814
#define IDM_ANIMATION_PREVIOUSFRAME     32815
#define IDM_VIEW_TEXTURES               32818
#define ID_EDIT_DELETE                  37000
#define ID_EDIT_DELETE_BACK             37001
#define ID_EDIT_DELETE_WORD_BACK        37002
#define ID_EDIT_TAB                     37003
#define ID_EDIT_UNTAB                   37004
#define ID_EDIT_SWITCH_OVRMODE          37005
#define ID_EDIT_CHAR_LEFT               37100
#define ID_EDIT_EXT_CHAR_LEFT           37101
#define ID_EDIT_CHAR_RIGHT              37102
#define ID_EDIT_EXT_CHAR_RIGHT          37103
#define ID_EDIT_WORD_LEFT               37104
#define ID_EDIT_EXT_WORD_LEFT           37105
#define ID_EDIT_WORD_RIGHT              37106
#define ID_EDIT_EXT_WORD_RIGHT          37107
#define ID_EDIT_LINE_UP                 37108
#define ID_EDIT_EXT_LINE_UP             37109
#define ID_EDIT_LINE_DOWN               37110
#define ID_EDIT_EXT_LINE_DOWN           37111
#define ID_EDIT_SCROLL_UP               37112
#define ID_EDIT_SCROLL_DOWN             37113
#define ID_EDIT_PAGE_UP                 37114
#define ID_EDIT_EXT_PAGE_UP             37115
#define ID_EDIT_PAGE_DOWN               37116
#define ID_EDIT_EXT_PAGE_DOWN           37117
#define ID_EDIT_LINE_END                37118
#define ID_EDIT_EXT_LINE_END            37119
#define ID_EDIT_HOME                    37120
#define ID_EDIT_EXT_HOME                37121
#define ID_EDIT_TEXT_BEGIN              37122
#define ID_EDIT_EXT_TEXT_BEGIN          37123
#define ID_EDIT_TEXT_END                37124
#define ID_EDIT_EXT_TEXT_END            37125
#define ID_EDIT_FIND_PREVIOUS           37126
#define ID_EDIT_FIND_PREVIOUS2          37127
#define ID_EDIT_TOGGLE_BOOKMARK0        37200
#define ID_EDIT_TOGGLE_BOOKMARK1        37201
#define ID_EDIT_TOGGLE_BOOKMARK2        37202
#define ID_EDIT_TOGGLE_BOOKMARK3        37203
#define ID_EDIT_TOGGLE_BOOKMARK4        37204
#define ID_EDIT_TOGGLE_BOOKMARK5        37205
#define ID_EDIT_TOGGLE_BOOKMARK6        37206
#define ID_EDIT_TOGGLE_BOOKMARK7        37207
#define ID_EDIT_TOGGLE_BOOKMARK8        37208
#define ID_EDIT_TOGGLE_BOOKMARK9        37209
#define ID_EDIT_GO_BOOKMARK0            37210
#define ID_EDIT_GO_BOOKMARK1            37211
#define ID_EDIT_GO_BOOKMARK2            37212
#define ID_EDIT_GO_BOOKMARK3            37213
#define ID_EDIT_GO_BOOKMARK4            37214
#define ID_EDIT_GO_BOOKMARK5            37215
#define ID_EDIT_GO_BOOKMARK6            37216
#define ID_EDIT_GO_BOOKMARK7            37217
#define ID_EDIT_GO_BOOKMARK8            37218
#define ID_EDIT_GO_BOOKMARK9            37219
#define ID_EDIT_CLEAR_BOOKMARKS         37220
#define ID_EDIT_TOGGLE_BOOKMARK         37223
#define ID_EDIT_GOTO_NEXT_BOOKMARK      37224
#define ID_EDIT_GOTO_PREV_BOOKMARK      37225
#define ID_EDIT_CLEAR_ALL_BOOKMARKS     37226
#define ID_EDIT_INDICATOR_COL           37900
#define ID_EDIT_INDICATOR_READ          37901
#define ID_EDIT_INDICATOR_CRLF          37902
#define ID_EDIT_INDICATOR_POSITION      37903
#define ID_READONLYATTRIBUTES           37904
#define ID_BUTTON37905                  37905
#define ID_EXPANDALL                    37907

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2024
#define _APS_NEXT_COMMAND_VALUE         37908
#define _APS_NEXT_CONTROL_VALUE         2064
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
